--DROP TABLES
DROP TABLE IF EXISTS Supply;
DROP TABLE IF EXISTS Prepare;
DROP TABLE IF EXISTS ProductIngredient;
DROP TABLE IF EXISTS Place;
DROP TABLE IF EXISTS Supplier;
DROP TABLE IF EXISTS Product;
DROP TABLE IF EXISTS OrderDetail;
DROP TABLE IF EXISTS Store;
DROP TABLE IF EXISTS Customer;

--DROP VIEWS
DROP VIEW IF EXISTS RegularCustomers;
DROP VIEW IF EXISTS TopPerformingStore;
DROP VIEW IF EXISTS IngredientPrice;
DROP VIEW IF EXISTS QuantitySold;
DROP VIEW IF EXISTS CostOfOneDrink;
DROP VIEW IF EXISTS Costing;
DROP VIEW IF EXISTS SellingPriceOfOneDrink;
DROP VIEW IF EXISTS ProfitGenerated;
DROP VIEW IF EXISTS BestAndLeastProduct;